#!/usr/bin/python
"""Create a host list from the given easylist repo."""
# Usage: abp_hosts.py <input_directory> <output_file>

import os
import re
import sys

HOST_REGEXP = re.compile("[|]{2}([a-z0-9]+([.][a-z0-0]+)+)\\^$")

def find_hosts(filename, f_out):
  f_in = open(filename, "r")
  for line in f_in.readlines():
    m = re.match(HOST_REGEXP, line)
    if m and m.group(1):
      f_out.write("%s\n" % (m.group(1), ))

def main():
  """Read the easylist repo and output matching hosts."""
  if len(sys.argv) < 3:
    sys.exit("Usage: abp_hosts.py <input_directory> <output_file>")

  f_out = open(sys.argv[2], "w")
  f_out.write("// This file is automatically generated by abp_hosts.py\n")

  for root, dirs, files in os.walk(sys.argv[1]):
    # Process all of the files, one by one
    if root.find(".hg") != -1:
      continue
    for name in files:
      find_hosts(os.path.join(root, name), f_out)

  f_out.close()

if __name__ == "__main__":
  main()

